/** Tailwind build config (replaces the inline config the page used with the Tailwind CDN script). */
/** @type {import("tailwindcss").Config} */
const SANS = ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'];
const MONO = ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'];

module.exports = {
  content: ['./src/public/dashboard.html', './src/public/dashboard.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'secondary-container': '#dae2fd',
        outline: '#707881',
        'error-container': '#ffdad6',
        'on-background': '#0b1c30',
        'on-primary-fixed': '#001d31',
        'on-tertiary-fixed': '#00174b',
        'telemetry-indigo': '#6366F1',
        'surface-card': '#FFFFFF',
        'tertiary-fixed-dim': '#b4c5ff',
        'surface-container-high': '#dce9ff',
        'surface-dim': '#cbdbf5',
        'tertiary-fixed': '#dbe1ff',
        'outline-variant': '#bfc7d2',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'surface-bright': '#f8f9ff',
        'on-secondary-container': '#5c647a',
        'on-surface': '#0b1c30',
        'primary-fixed-dim': '#93ccff',
        'border-subtle': '#E2E8F0',
        'telemetry-emerald': '#10B981',
        'surface-container-lowest': '#ffffff',
        'telemetry-rose': '#F43F5E',
        'primary-fixed': '#cce5ff',
        'on-primary-fixed-variant': '#004b73',
        'surface-tint': '#006398',
        'on-tertiary': '#ffffff',
        'surface-canvas': '#F8FAFC',
        'surface-variant': '#d3e4fe',
        secondary: '#565e74',
        'primary-container': '#007bb9',
        'on-primary-container': '#fdfcff',
        'on-surface-variant': '#3f4850',
        primary: '#006194',
        'telemetry-amber': '#F59E0B',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary-container': '#fefcff',
        'secondary-fixed-dim': '#bec6e0',
        'r-accent': '#0EA5E9',
        'border-strong': '#CBD5E1',
        'inverse-surface': '#213145',
        'on-tertiary-fixed-variant': '#003ea8',
        tertiary: '#0051d5',
        'tertiary-container': '#316bf3',
        'surface-container-low': '#eff4ff',
        surface: '#f8f9ff',
        background: '#f8f9ff',
        'on-error-container': '#93000a',
        'inverse-primary': '#93ccff',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed-variant': '#3f465c',
        'secondary-fixed': '#dae2fd',
        'on-secondary-fixed': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        card: '1rem',
      },
      spacing: {
        gutter: '1rem',
        'space-md': '0.75rem',
        'space-sm': '0.5rem',
        'space-3xl': '3rem',
        'margin-desktop': '2rem',
        'space-xl': '1.5rem',
        'gutter-desktop': '1.5rem',
        'space-2xl': '2rem',
        'space-2xs': '0.125rem',
        'space-lg': '1rem',
        'space-xs': '0.25rem',
        margin: '1rem',
      },
      fontFamily: {
        'label-sm': SANS,
        'code-md': MONO,
        'display-lg': SANS,
        'body-md': SANS,
        'headline-md': SANS,
        'headline-lg-mobile': SANS,
        'body-lg': SANS,
        'label-md': SANS,
        'headline-sm': SANS,
        'headline-lg': SANS,
        'code-sm': MONO,
        'body-sm': SANS,
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': [
          '20px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        'code-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
