#!/usr/bin/env node
/**
 * Generates src/public/icons.svg, the inline SVG sprite used by the dashboard
 * (`<svg class="icon"><use href="/icons.svg#name"/></svg>`).
 *
 * Source: @material-design-icons/svg (Material Icons, "outlined" style, Apache-2.0), a pinned devDependency.
 * The sprite is committed so the runtime and the Docker image need no devDependency; re-run
 * `npm run build:icons` after changing ICONS (tests/unit/dashboard-assets.test.ts checks that every icon
 * the dashboard references exists in the sprite).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = [
  'auto_awesome',
  'description',
  'download',
  'error',
  'expand_more',
  'filter_list',
  'folder',
  'menu_book',
  'monitor_heart',
  'play_circle',
  'radar',
  'refresh',
  'tune',
  'upload_file',
  'verified',
  'warning',
];

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'node_modules', '@material-design-icons', 'svg', 'outlined');

const symbols = ICONS.map((name) => {
  const svg = readFileSync(path.join(srcDir, `${name}.svg`), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  if (/<(script|style|image|use|foreignObject)\b/i.test(inner)) {
    throw new Error(`unsafe icon ${name}`);
  }
  return `<symbol id="${name}" viewBox="0 0 24 24">${inner}</symbol>`;
});

const out =
  '<svg xmlns="http://www.w3.org/2000/svg">\n' +
  '<!-- Generated by scripts/build-icons.mjs from @material-design-icons/svg (Apache-2.0). Do not edit. -->\n' +
  symbols.join('\n') +
  '\n</svg>\n';
writeFileSync(path.join(root, 'src', 'public', 'icons.svg'), out);
console.log(`icons.svg: ${ICONS.length} icons, ${out.length} bytes`);
